name: movies
description: "Discover the ultimate streaming companion that brings the world of entertainment to your fingertips. "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.1
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.15
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: any
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.2
  sliver_tools: ^0.2.12
  smooth_page_indicator: ^1.2.0+3
  webview_flutter: ^4.10.0
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/icons/
    - .env

flutter_intl:
  enabled: true
